# Generated by Django 4.1.3 on 2022-12-07 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_servico',
            name='descricao_chamado',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='numero_chamado',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='status',
            field=models.CharField(choices=[('P', 'Parado'), ('R', 'Restrito'), ('N', 'Normal'), ('O', 'Outros')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='tipo_chamado',
            field=models.CharField(choices=[('C', 'Contrato'), ('A', 'Avulso')], default='C', max_length=1),
        ),
    ]
