# Generated by Django 4.1.3 on 2022-12-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0004_ordem_servico_equipamento_alter_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_servico',
            name='status_chamado',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1),
        ),
    ]
