# Generated by Django 4.1.3 on 2022-12-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0014_rename_dia_cargahoraria_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargahoraria',
            name='Ordem_Servico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orion.ordem_servico'),
            preserve_default=False,
        ),
    ]
