# Generated by Django 4.1.3 on 2023-02-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0019_alter_cargahoraria_ordem_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='contato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orion.contato'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orion.endereco'),
        ),
    ]
