# Generated by Django 4.1.3 on 2023-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0023_alter_ordem_servico_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargahoraria',
            name='horas_de_trabalho',
            field=models.TimeField(default='00:00', editable=False),
            preserve_default=False,
        ),
    ]
