# Generated by Django 4.1.3 on 2023-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0026_alter_empresa_email_alter_empresa_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_servico',
            name='descricao_servico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='observacoes_do_cliente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
