# Generated by Django 4.1.3 on 2023-03-04 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0027_alter_ordem_servico_descricao_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_servico',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orion.equipamento'),
        ),
    ]
