# Generated by Django 4.1.3 on 2023-03-06 17:24

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0029_signaturemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_servico',
            name='assinatura',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
