# Generated by Django 4.1.3 on 2023-03-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_alter_usuario_tipo"),
        ("orion", "0032_despesa"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargahoraria",
            name="tecnico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carga_horaria",
                to="usuarios.usuario",
            ),
        ),
    ]
