# Generated by Django 4.1.3 on 2023-03-20 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orion", "0034_alter_cargahoraria_tecnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="tecnico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="despesa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
