# Generated by Django 4.1.3 on 2023-04-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_alter_usuario_tipo"),
        ("orion", "0035_despesa_tecnico"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ordem_Servico",
            new_name="Chamado",
        ),
    ]
