# Generated by Django 4.1.3 on 2022-12-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0005_ordem_servico_status_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_servico',
            name='aberto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orion.usuario'),
        ),
    ]
