# Generated by Django 4.1.3 on 2022-12-08 05:00

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0006_ordem_servico_aberto_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_servico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orion.empresa'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='equipamento',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='empresa', chained_model_field='Empresa', default=1, on_delete=django.db.models.deletion.CASCADE, to='orion.equipamento'),
            preserve_default=False,
        ),
    ]
