# Generated by Django 4.1.3 on 2022-12-08 21:53

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0007_ordem_servico_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_servico',
            name='Contato',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='contato', chained_model_field='empresa', default=1, on_delete=django.db.models.deletion.CASCADE, to='orion.contato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='equipamento',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='empresa', chained_model_field='empresa', on_delete=django.db.models.deletion.CASCADE, to='orion.equipamento'),
        ),
    ]
