# Generated by Django 4.1.3 on 2022-12-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0009_remove_ordem_servico_contato_ordem_servico_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_servico',
            name='descricao_servico',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='observacoes_do_cliente',
            field=models.TextField(blank=True),
        ),
    ]
