# Generated by Django 4.1.3 on 2022-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0012_rename_nome_contato_nomecontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField()),
            ],
        ),
    ]
