# Generated by Django 4.1.3 on 2022-12-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0013_cargahoraria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargahoraria',
            old_name='dia',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='cargahoraria',
            old_name='entrada',
            new_name='hora_inicio',
        ),
        migrations.RenameField(
            model_name='cargahoraria',
            old_name='saida',
            new_name='hora_termino',
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='status',
            field=models.CharField(choices=[('P', 'Parado'), ('R', 'Restrito'), ('N', 'Normal'), ('O', 'Outros')], default='N', max_length=1),
        ),
    ]
