# Generated by Django 4.1.3 on 2022-12-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0015_cargahoraria_ordem_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargahoraria',
            name='Ordem_Servico',
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='ordem_Servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carga_horaria', to='orion.ordem_servico'),
            preserve_default=False,
        ),
    ]
