# Generated by Django 4.1.3 on 2023-02-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0017_rename_ordem_servico_cargahoraria_ordem_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('A', 'Admin'), ('T', 'Tecnico')], max_length=1),
        ),
    ]
