# Generated by Django 4.1.3 on 2023-02-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('orion', '0018_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargahoraria',
            name='ordem_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_horaria', to='orion.ordem_servico'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='aberto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
