# Generated by Django 4.1.3 on 2023-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0021_alter_empresa_contato_alter_empresa_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='contato',
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='contato',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
