# Generated by Django 4.1.3 on 2023-03-19 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orion", "0033_cargahoraria_tecnico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargahoraria",
            name="tecnico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carga_horaria",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
